### ISSUE TITLE
TODO before 2.0.0

### ISSUE THREAD

**Issue by goneri** [ansible-collections/vmware_rest_code_generator#110]
- [x] address the sanity test issues
- [x] prepare a manual that cover the application modules
- [ ] add test for the library modules (See: https://github.com/ansible-collections/vmware.vmware_rest/pull/174)
- [ ] list the breaking changes between since 1.0.0
- [ ] add a test to spot pre-7.0.2 vCenter and bailout
- [ ] identify the new vcenter modules and test them
